---
version: '3.2'

services:
  www:
    build:
      context: .
      args:
        http_proxy: $http_proxy
    image: docker-registry-default.dev-apps.environment.gov.au/common/www:latest
    ports:
      - 80:8080




