---
# This file is used to configure the project in OpenShift


# The description shows in the My Projects page in OpenShift.
# It should be the full name of the business product, or it should describe what the project contains.
openShiftProjectDescription: Common builds and services for all projects.

# Applications in this project need to be able to pull images from other projects: 
#imagePullAccess: 
#  - base
#  - common
#  - s2i
