---
# OpenShift Image Builds

apiVersion: v1
kind: Template
metadata:
  name: builds

# -------- Parameters (populated by lib-jenkins) -------
parameters:

- name: PROJECT
  description: "The OpenShift project name, aka namespace."

- name: PRODUCT
  description: "The product value of the product-function naming convention."
  
- name: FUNCTION
  description: "The function value of the product-function naming convention."

- name: FROM_IMAGE
  description: "The image referenced by the FROM line of the Dockerfile. Needed when images are pulled from the OpenShift registry."

- name: SOURCE
  description: "Url to the git source repository"

objects:

# -------- Main application ----------------

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${PRODUCT}-${FUNCTION}
    namespace: ${PROJECT}
  spec:
    runPolicy: Serial
    triggers: []
    source:
      type: Git
      contextDir: .
      git:
        ref: master
        uri: ${SOURCE}
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: ${PRODUCT}-${FUNCTION}:latest

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${PRODUCT}-${FUNCTION}
    namespace: ${PROJECT}
